baseURL = 'https://blog.sunisalex.org/'
languageCode = 'zh-cn'
title = '∅AxiomLab'
theme = 'FixIt'
enableRobotsTXT = true

[outputFormats.search]
baseName = "search"
mediaType = "application/json"
rel = "search"
isPlainText = true
isHTML = false
permalinkable = true

[outputs]
home = [
  "html",
  "rss",
  "archives",
  "offline",
  "search"
]
page = [
  "html",
  "markdown"
]
section = [
  "html",
  "rss"
]
taxonomy = [ "html" ]
term = [
  "html",
  "rss"
]
[params]
  capitalizeTitles = false     # 关闭 FixIt 的标题自动大写
[params.search]
enable = true
type = "fuse"
contentLength = 4000
placeholder = "搜索文章标题或内容..."
maxResultLength = 10
snippetLength = 30
highlightTag = "em"
absoluteURL = false
anchorify = true

[params.search.fuse]
isCaseSensitive = false
minMatchCharLength = 2
findAllMatches = false
location = 0
threshold = 0.3
distance = 100
ignoreLocation = false
useExtendedSearch = false
ignoreFieldNorm = false

[markup]

[markup.goldmark]
[markup.goldmark.renderer]
         unsafe = true
[markup.goldmark.extensions]

[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [
  [
    '\[',
    '\]'
  ],
  [
    '$$',
    '$$'
  ]
]
inline = [
  [
    '\(',
    '\)'
  ],
  [
    '$',
    '$'
  ]
]

[params.page]

[params.page.math]
enable = true
type = "katex"


[params.busuanzi]
enable = true
pageViews = true
siteViews = true
source = 'https://vercount.one/js'

[params.cookieconsent]
enable = false
[[menu.main]]
  identifier = 'tags'
  name       = 'Tags'
  url        = '/tags/'
  weight     = 10
  [menu.main.params]
    icon = 'fa-solid fa-tags'

[[menu.main]]
  identifier = 'categories'
  name       = 'Categories'
  url        = '/categories/'
  weight     = 20
  [menu.main.params]
    icon = 'fa-solid fa-folder-open'

[params.app]
  title = "∅AxiomLab"
  iconColor = ""
  tileColor = "#ffffff"
