baseURL = 'https://blog.sunisalex.org/'
languageCode = 'zh-cn'
title = '∅AxiomLab'
theme = 'FixIt'
enableRobotsTXT = true
[params]
  capitalizeTitles = false     # 关闭 FixIt 的标题自动大写
[markup]

[markup.goldmark]
[markup.goldmark.renderer]
         unsafe = true
[markup.goldmark.extensions]

[markup.goldmark.extensions.passthrough]
enable = true

[markup.goldmark.extensions.passthrough.delimiters]
block = [
  [
    '\[',
    '\]'
  ],
  [
    '$$',
    '$$'
  ]
]
inline = [
  [
    '\(',
    '\)'
  ],
  [
    '$',
    '$'
  ]
]

[params.page]

[params.page.math]
enable = true
type = "katex"


[params.busuanzi]
enable = true
pageViews = true
siteViews = true
source = 'https://vercount.one/js'

[params.cookieconsent]
enable = false
[[menu.main]]
  identifier = 'tags'
  name       = 'Tags'
  url        = '/tags/'
  weight     = 10
  [menu.main.params]
    icon = 'fa-solid fa-tags'

[[menu.main]]
  identifier = 'categories'
  name       = 'Categories'
  url        = '/categories/'
  weight     = 20
  [menu.main.params]
    icon = 'fa-solid fa-folder-open'

[[menu.main]]
  identifier = 'nav'
  name       = 'Navigation'
  url        = 'https://app.sunisalex.org'
  weight     = 30
  [menu.main.params]
    icon = 'fa-solid fa-globe'
